# Generated by Django 5.1.1 on 2024-09-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_extrabooks_subject"),
    ]

    operations = [
        migrations.AddField(
            model_name="extrabooks",
            name="is_collective",
            field=models.BooleanField(default=False),
        ),
    ]
